/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg10_lab;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author chung
 */
public class AddNewFruit extends javax.swing.JFrame {

    /**
     * Creates new form AddNewFruit
     */
    public AddNewFruit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_fruitName = new javax.swing.JLabel();
        input_fruitName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        label_quantity = new javax.swing.JLabel();
        input_quantity = new javax.swing.JTextField();
        input_price = new javax.swing.JTextField();
        label_price = new javax.swing.JLabel();
        label_supplierName = new javax.swing.JLabel();
        input_supplierName = new javax.swing.JTextField();
        button_addMore = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        label_fruitName.setText("Fruit Name:");

        input_fruitName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_fruitNameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add New Fruit");

        label_quantity.setText("Quantity:");

        input_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_quantityActionPerformed(evt);
            }
        });

        label_price.setText("Price (RM):");

        label_supplierName.setText("Supplier Name:");

        button_addMore.setText("Add More");
        button_addMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_addMoreActionPerformed(evt);
            }
        });

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_fruitName)
                        .addGap(18, 18, 18)
                        .addComponent(input_fruitName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(label_quantity)
                        .addGap(18, 18, 18)
                        .addComponent(input_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_supplierName)
                        .addGap(18, 18, 18)
                        .addComponent(input_supplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(label_price)
                        .addGap(18, 18, 18)
                        .addComponent(input_price, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_addMore, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(274, 274, 274))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_fruitName)
                    .addComponent(input_fruitName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_quantity)
                    .addComponent(input_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_supplierName)
                    .addComponent(input_supplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_price)
                    .addComponent(input_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(button_addMore)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_addMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_addMoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_addMoreActionPerformed

    private void input_fruitNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_fruitNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_input_fruitNameActionPerformed


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (input_fruitName.getText().isEmpty() || 
            input_quantity.getText().isEmpty() ||
            input_supplierName.getText().isEmpty() ||
            input_price.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please ensure all fields are populated");
        }else{
            
            String fruitName = input_fruitName.getText();
            String quantity = input_quantity.getText();
            String supplierName = input_supplierName.getText();
            String price = input_price.getText();
                
            try {
                File recordFile = new File("D:\\git-repos\\JavaProgramming\\10_Lab\\src\\pkg10_lab\\record.txt");
                FileWriter fileWriter = new FileWriter(recordFile);

                BufferedWriter bufferWriter = new BufferedWriter(fileWriter);

                String line = fruitName + "," + quantity + "," + price + "," + supplierName + "\n";
        
                bufferWriter.write(line);
                bufferWriter.close();
                
                JOptionPane.showMessageDialog(null, "Fruit added");
                
                /*
                    while (choice.equals("C")) {
                    System.out.print("Fruit name: ");
                    String fruitname = sc.next();

                    System.out.print("Quantity: ");
                    int quantity = sc.nextInt();

                    System.out.print("Price: ");
                    double price = sc.nextDouble();

                    System.out.print("Supplier: ");
                    sc.nextLine();
                    String supplier = sc.nextLine();

                    String line = fruitname + "," + quantity + "," + price + "," + supplier + "\n";
                    System.out.println("C for continue, X for exit: ");
                    choice = sc.next();
                */

            } catch (Exception e) {
                System.out.println("Error");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void input_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_quantityActionPerformed

    /**
     * @param args the command line arguments
     */
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewFruit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewFruit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewFruit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewFruit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewFruit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_addMore;
    private javax.swing.JTextField input_fruitName;
    private javax.swing.JTextField input_price;
    private javax.swing.JTextField input_quantity;
    private javax.swing.JTextField input_supplierName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel label_fruitName;
    private javax.swing.JLabel label_price;
    private javax.swing.JLabel label_quantity;
    private javax.swing.JLabel label_supplierName;
    // End of variables declaration//GEN-END:variables
}


